@startmindmap teste
* Atividades Acadêmicas
** Pesquisa
*** Iniciação Científica
*** Seminários
*** Workshops
-- Extensão
--- Projetos Comunitários
--- Voluntariado
--- Consultoria
-- Ensino
--- Monitorias
--- Tutoria
--- Aulas Práticas
** Desenvolvimento Profissional
** Liderança
*** <s>Raspmbc</s> => OSMC
*** <s>Raspyfi</s> => Volumio
@endmindmap



ndmap teste
    root((Atividades Acadêmicas<br/>Complementares))
        Pesquisa
            Iniciação Científica
            Seminários
            Workshops
        Extensão
            Projetos Comunitários
            Voluntariado
            Consultoria
        Ensino
            Monitorias
            Tutoria
            Aulas Práticas
        Desenvolvimento Profissional
            Certificações
            Cursos Online
            Congressos
        Liderança
            Diretórios Acadêmicos
            Representação Estudantil
            Coordenação de Eventos